# Generated by Django 5.2 on 2025-04-22 05:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('contact_phone', models.CharField(max_length=11, verbose_name='Контактный номер')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('rating', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефонный номер')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('passport_seria', models.IntegerField(verbose_name='Серия паспорта')),
                ('passport_num', models.IntegerField(verbose_name='Номер паспорта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Reviews_and_ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.clients', verbose_name='Клиент')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Отзыв и оценка',
                'verbose_name_plural': 'Отзывы и оценки',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Одноместный'), (1, 'Двуместный'), (2, 'Люкс')], verbose_name='Тип комнаты')),
                ('minbar', models.BooleanField(default=True, verbose_name='Мини-Бар')),
                ('conditioner', models.BooleanField(default=True, verbose_name='Кондиционер')),
                ('television', models.BooleanField(default=True, verbose_name='Телевизор')),
                ('hairdryer', models.BooleanField(default=True, verbose_name='Фен')),
                ('safe', models.BooleanField(default=True, verbose_name='Сейф в номере')),
                ('Kettle_or_coffee_maker', models.BooleanField(default=True, verbose_name='Чайник или кофеварка')),
                ('Sound_insulation', models.BooleanField(default=True, verbose_name='Звукоизоляция')),
                ('Balcony_or_terrace', models.BooleanField(default=True, verbose_name='Балкон или терраса')),
                ('special_for_ivalid', models.BooleanField(default=True, verbose_name='Удобства для людей с ограниченными возможностями')),
                ('Telephone', models.BooleanField(default=True, verbose_name='Телефон')),
                ('Fridge', models.BooleanField(default=True, verbose_name='Холодильник')),
                ('Underfloor_heating', models.BooleanField(default=True, verbose_name='Пол с подогревом')),
                ('Work_facilities', models.BooleanField(default=True, verbose_name='Удобства для работы')),
                ('Baby_cot_services', models.BooleanField(default=True, verbose_name='Услуги по предоставлению детской кроватки')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField(verbose_name='Дата заезда')),
                ('departure_date', models.DateTimeField(verbose_name='Дата выезда')),
                ('total_amount', models.IntegerField(verbose_name='Общая сумма')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.clients', verbose_name='Клиент')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
