# Generated by Django 5.2 on 2025-04-20 08:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('contact_phone', models.CharField(max_length=11, verbose_name='Контактный номер')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефонный номер')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('passport_seria', models.IntegerField(verbose_name='Серия паспорта')),
                ('passport_num', models.IntegerField(verbose_name='Номер паспорта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Reviews_and_ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.IntegerField(verbose_name='Оценка')),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.clients')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.hotel')),
            ],
            options={
                'verbose_name_plural': 'Отзывы и оценки',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Одноместный'), (1, 'Двуместный'), (2, 'Люкс')], verbose_name='Тип комнат')),
                ('minbar', models.BooleanField(default=True, verbose_name='Мини-Бар')),
                ('conditioner', models.BooleanField(default=True, verbose_name='Кондиционер')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.hotel')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField(verbose_name='Дата заезда')),
                ('departure_date', models.DateTimeField(verbose_name='Дата выезда')),
                ('total_amount', models.IntegerField(verbose_name='Общая сумма')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.clients')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.room')),
            ],
            options={
                'verbose_name_plural': 'Отношения',
            },
        ),
    ]
