# Generated by Django 5.2 on 2025-04-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('contact_phone', models.CharField(max_length=11, verbose_name='Контактный номер')),
                ('email', models.CharField(verbose_name='Email')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
    ]
