# Generated by Django 5.2 on 2025-04-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='foto1',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='foto2',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='foto3',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='foto4',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='foto5',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='foto1',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='foto2',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Название отеля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=1, verbose_name='Номер комнаты'),
            preserve_default=False,
        ),
    ]
