# Generated by Django 5.2 on 2025-04-17 02:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Одноместный'), (1, 'Двуместный'), (2, 'Люкс')], verbose_name='Тип комнат')),
                ('minbar', models.BooleanField(default=True, verbose_name='Мини-Бар')),
                ('conditioner', models.BooleanField(default=True, verbose_name='Кондиционер')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.hotel')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
    ]
