# Generated by Django 5.2 on 2025-04-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_hotel_price_hotel_foto1_hotel_foto2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=50, verbose_name='Название комнаты'),
        ),
    ]
