# Generated by Django 5.2 on 2025-04-17 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_hotel_rating_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефонный номер')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('passport_seria', models.IntegerField(max_length=100, verbose_name='Серия паспорта')),
                ('passport_num', models.IntegerField(max_length=100, verbose_name='Номер паспорта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField(verbose_name='Дата заезда')),
                ('departure_date', models.DateTimeField(verbose_name='Дата выезда')),
                ('total_amount', models.IntegerField(verbose_name='Общая сумма')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.clients')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.room')),
            ],
            options={
                'verbose_name_plural': 'Отношения',
            },
        ),
        migrations.CreateModel(
            name='Reviews_and_ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.IntegerField(verbose_name='Оценка')),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.clients')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.hotel')),
            ],
            options={
                'verbose_name_plural': 'Отзывы и оценки',
            },
        ),
    ]
