# Generated by Django 5.2 on 2025-04-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_clients_alter_hotel_email_reservations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(default=6000, max_length=50, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
