# Generated by Django 5.2 on 2025-04-22 04:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_add_default_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='reviews_and_ratings',
            options={'verbose_name': 'Отзыв и оценка', 'verbose_name_plural': 'Отзывы и оценки'},
        ),
        migrations.RemoveField(
            model_name='clients',
            name='password',
        ),
        migrations.AddField(
            model_name='clients',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='Baby_cot_services',
            field=models.BooleanField(default=True, verbose_name='Услуги по предоставлению детской кроватки'),
        ),
        migrations.AddField(
            model_name='room',
            name='Balcony_or_terrace',
            field=models.BooleanField(default=True, verbose_name='Балкон или терраса'),
        ),
        migrations.AddField(
            model_name='room',
            name='Fridge',
            field=models.BooleanField(default=True, verbose_name='Холодильник'),
        ),
        migrations.AddField(
            model_name='room',
            name='Kettle_or_coffee_maker',
            field=models.BooleanField(default=True, verbose_name='Чайник или кофеварка'),
        ),
        migrations.AddField(
            model_name='room',
            name='Sound_insulation',
            field=models.BooleanField(default=True, verbose_name='Звукоизоляция'),
        ),
        migrations.AddField(
            model_name='room',
            name='TV',
            field=models.BooleanField(default=True, verbose_name='Телевизор'),
        ),
        migrations.AddField(
            model_name='room',
            name='Telephone',
            field=models.BooleanField(default=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='room',
            name='Underfloor_heating',
            field=models.BooleanField(default=True, verbose_name='Пол с подогревом'),
        ),
        migrations.AddField(
            model_name='room',
            name='Work_facilities',
            field=models.BooleanField(default=True, verbose_name='Удобства для работы'),
        ),
        migrations.AddField(
            model_name='room',
            name='hairdryer',
            field=models.BooleanField(default=True, verbose_name='Фен'),
        ),
        migrations.AddField(
            model_name='room',
            name='safe',
            field=models.BooleanField(default=True, verbose_name='Сейф в номере'),
        ),
        migrations.AddField(
            model_name='room',
            name='special_for_ivalid',
            field=models.BooleanField(default=True, verbose_name='Удобства для людей с ограниченными возможностями'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='passport_num',
            field=models.IntegerField(verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='passport_seria',
            field=models.IntegerField(verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.clients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='reviews_and_ratings',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.clients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='reviews_and_ratings',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='reviews_and_ratings',
            name='estimation',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='reviews_and_ratings',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.IntegerField(choices=[(0, 'Одноместный'), (1, 'Двуместный'), (2, 'Люкс')], verbose_name='Тип комнаты'),
        ),
    ]
