# Generated by Django 5.2 on 2025-04-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_reservations_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='TV',
            new_name='television',
        ),
    ]
