# Generated by Django 5.2 on 2025-04-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_tv_room_television'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='television',
        ),
    ]
