# Generated by Django 5.2 on 2025-04-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_room_television'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='television',
            field=models.BooleanField(default=True, verbose_name='Телевизор'),
        ),
    ]
